#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
project="$repo_root/prototypes/one-plus-one-minus-one"
release_env="$project/RELEASE_ENV.example"
store_metadata="$repo_root/docs/one-equals-one-store-metadata-draft.md"
privacy_policy="$repo_root/docs/privacy-policy.md"

bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl.sh"
bash -n "$repo_root/scripts/check-one-plus-one-minus-one-unity-license.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-unity-license.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-platform-readiness-preflight.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-release-env.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-device-qa-signoff.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-store-metadata.sh"
bash -n "$repo_root/scripts/test-one-plus-one-minus-one-ship-ready.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-playmode.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-qa.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-shells.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
bash -n "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-build.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-webgl-qa-rounds.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-round-select-pages.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-app-store-candidates.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
bash -n "$repo_root/scripts/lib-one-plus-one-minus-one-unity-license.sh"
grep -Fq "Unity licensing client is unavailable" "$repo_root/scripts/lib-one-plus-one-minus-one-unity-license.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/check-one-plus-one-minus-one-unity-license.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-playmode.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
bash -n "$repo_root/scripts/refresh-one-plus-one-minus-one-visual-qa.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-icon.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
node --check "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-viewports.mjs"
node --check "$repo_root/scripts/playtest-one-plus-one-minus-one-webgl.mjs"
node "$repo_root/scripts/test-one-plus-one-minus-one-viewport-bridge.mjs"
bash "$repo_root/scripts/test-one-plus-one-minus-one-unity-license.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-platform-readiness-preflight.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-release-env.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-device-qa-signoff.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-store-metadata.sh"
bash "$repo_root/scripts/test-one-plus-one-minus-one-ship-ready.sh"
node --test "$repo_root/scripts/test-one-plus-one-minus-one-cdp-client.mjs"
node --test "$repo_root/scripts/test-one-plus-one-minus-one-round-identity.mjs"
node --check "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
grep -Fq "Shared Equality Witnesses (Reuse Review)" "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
grep -Fq "intentionalReason" "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
grep -Fq "early tutorial echo" "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
grep -Fq "title callback" "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
node --check "$repo_root/scripts/strip-png-alpha.mjs"
node --check "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
node --check "$repo_root/scripts/verify-one-plus-one-minus-one-png-visuals.mjs"
node --check "$repo_root/scripts/verify-one-plus-one-minus-one-icon-visuals.mjs"

"$repo_root/scripts/verify-one-plus-one-minus-one-rounds.mjs"
"$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs" --strict
"$repo_root/scripts/verify-one-plus-one-minus-one-icon.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
"$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
"$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-build.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-webgl-shells.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"

grep -Fq "Bundle ID: \`com.mannlab.games.oneplusoneminusone\`" "$store_metadata"
grep -Fq "Privacy policy URL: \`https://games.mannlab.app/privacy\`" "$store_metadata"
grep -Fq "1 = 1 may use Firebase Analytics" "$privacy_policy"
grep -Fq "Strict readiness rejects" "$project/STORE_READINESS.md"
grep -Fq "NSPrivacyAccessedAPICategoryUserDefaults" "$project/Assets/_Project/Store/PrivacyInfo.xcprivacy"
grep -Fq "CA92.1" "$project/Assets/_Project/Store/PrivacyInfo.xcprivacy"
grep -Fq "AddPrivacyManifestToXcodeProject" "$project/Assets/_Project/Editor/BuildIosXcode.cs"
grep -Fq "PrivacyInfo.xcprivacy" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_IOS_APP_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_IOS_INTERSTITIAL_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_ANDROID_APP_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_ANDROID_INTERSTITIAL_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ANDROID_KEYSTORE_PATH" "$release_env"
grep -Fq "intentionally fail strict readiness" "$release_env"
grep -Fq "Production AdMob env uses a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq 'Firebase $label config not present yet' "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "Production AdMob env has invalid format" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "Production AdMob env uses Google's test ID" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "ONE_EQUALS_ONE_FIREBASE_IOS_CONFIG" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "AdMob/Crashlytics readiness tests passed" "$repo_root/scripts/test-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "has_placeholder_text" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "release environment preflight" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq -- "--strict fails on every missing" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "REQUIRE_ONE_EQUALS_ONE_RELEASE_ENV" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "ONE_EQUALS_ONE_FIREBASE_IOS_CONFIG" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "ONE_EQUALS_ONE_FIREBASE_ANDROID_CONFIG" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "Required external release inputs" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "bookkeeping even when some files are already present" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ANDROID_KEYSTORE_PATH should be an absolute path" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "has_placeholder_text" "$repo_root/scripts/verify-one-plus-one-minus-one-release-env.sh"
grep -Fq "release environment tests passed" "$repo_root/scripts/test-one-plus-one-minus-one-release-env.sh"
grep -Fq "device QA signoff" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "REQUIRE_ONE_EQUALS_ONE_DEVICE_QA" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "Required manual QA signoff inputs" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "ONE_EQUALS_ONE_DEVICE_QA_TRACKER" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "unknown Status value" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "terminal Status row" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "cannot be ready for TestFlight/internal test while External blockers remain" "$repo_root/scripts/verify-one-plus-one-minus-one-device-qa-signoff.sh"
grep -Fq "ONE_EQUALS_ONE_STORE_METADATA" "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "keyword-spacing failure text" "$repo_root/scripts/test-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "screenshot slug failure text" "$repo_root/scripts/test-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "Numerical Fix Runtime Pending" "$repo_root/docs/one-equals-one-device-qa-tracker.md"
grep -Fq "include this local candidate" "$repo_root/docs/one-equals-one-device-qa-tracker.md"
grep -Fq "actual input confirmation that Round 48 rejects \`1 / 11 111\`" "$repo_root/docs/one-equals-one-device-qa-tracker.md"
grep -Fq "Current Runtime Caveat" "$project/STORE_READINESS.md"
grep -Fq "The local source is newer than uploaded iOS \`1.0.0 (2)\`" "$project/STORE_READINESS.md"
grep -Fq "\`Assets/GoogleService-Info.plist\` is present locally" "$project/STORE_READINESS.md"
grep -Fq "Android Firebase json is still missing" "$repo_root/docs/one-equals-one-commercial-polish-backlog.md"
grep -Fq "iOS plist present locally" "$repo_root/docs/one-equals-one-ship-ready-status.md"
grep -Fq "check-one-plus-one-minus-one-unity-license.sh" "$project/README.md"
grep -Fq "ios-readiness.sh release --preflight-only" "$project/README.md"
grep -Fq "android-readiness.sh release --preflight-only" "$project/README.md"
grep -Fq "ios-readiness.sh release --preflight-only" "$project/STORE_READINESS.md"
grep -Fq "android-readiness.sh release --preflight-only" "$project/STORE_READINESS.md"
grep -Fq "Production iOS AdMob App ID is a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "Production iOS AdMob App ID has invalid format" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "Production iOS AdMob App ID is not set" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "has_placeholder_text" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq -- "--preflight-only" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "ONE_EQUALS_ONE_FIREBASE_IOS_CONFIG" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_IOS_BUILD_NUMBER should be a positive integer" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "readiness failed before Unity export" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "Production Android AdMob App ID is a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "Production Android AdMob App ID has invalid format" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "Production Android AdMob App ID is not set" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "has_placeholder_text" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq -- "--preflight-only" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "ONE_EQUALS_ONE_FIREBASE_ANDROID_CONFIG" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ANDROID_KEYSTORE_PATH should be an absolute path" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ANDROID_VERSION_CODE should be a positive integer" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "platform readiness preflight tests passed" "$repo_root/scripts/test-one-plus-one-minus-one-platform-readiness-preflight.sh"
grep -Fq "Unable to open local WebGL smoke port" "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-viewports.mjs"
grep -Fq "apple-mobile-web-app-title" "$project/Assets/_Project/Editor/BuildWebGL.cs"
grep -Fq "apple-touch-icon" "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-build.sh"
grep -Fq "apple-touch-icon" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-qa.sh"
grep -Fq "apple-touch-icon" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh"
grep -Fq "Store-capture" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-shells.sh"
grep -Fq "No Unity Editor license found" "$repo_root/scripts/lib-one-plus-one-minus-one-unity-license.sh"
grep -Fq "WebGL artifact freshness failed" "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
grep -Fq "strict iOS release preflight" "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
grep -Fq "strict Android release preflight" "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
grep -Fq "DisplaysTinyNonzeroResultWithoutRoundingToZero" "$project/Assets/_Project/Tests/EditMode/OnePlusOneMinusOneRulesTests.cs"
grep -Fq "GoalRoundTargetsStayIntegerForExactAcceptance" "$project/Assets/_Project/Tests/EditMode/OnePlusOneMinusOneRulesTests.cs"
grep -Fq "release goal rounds keep integer targets for exact acceptance" "$repo_root/scripts/test-one-plus-one-minus-one-round-identity.mjs"
grep -Fq 'value.Numerator.ToString' "$project/Assets/_Project/Scripts/OnePlusOneMinusOneRules.cs"
grep -Fq "Solve acceptance must stay exact-rational" "$project/Assets/_Project/Scripts/OnePlusOneMinusOneRules.cs"
target_tolerance_runtime_refs="$(rg -n "TargetTolerance" "$project/Assets/_Project/Scripts" -g '*.cs' | grep -v "public const double TargetTolerance" | grep -v "Legacy double-test/display tolerance" || true)"
if [[ -n "$target_tolerance_runtime_refs" ]]; then
  echo "TargetTolerance must not be used by runtime solve acceptance:" >&2
  echo "$target_tolerance_runtime_refs" >&2
  exit 1
fi
grep -Fq "CalculatedValueFailureText" "$project/Assets/_Project/Scripts/OnePlusOneMinusOneController.cs"
grep -Fq "ValidWrongResultFeedbackReusesExactReasonText" "$project/Assets/_Project/Tests/PlayMode/StickInteractionTests.cs"
grep -Fq "Makes 1/111111111." "$project/Assets/_Project/Tests/PlayMode/StickInteractionTests.cs"
grep -Fq 'saying `Makes 0.`' "$repo_root/docs/one-equals-one-gameplay-quality-audit.md"
grep -Fq 'separate `Makes 0.` fallback path' "$repo_root/docs/one-equals-one-commercial-polish-backlog.md"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-qa.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "check_one_plus_one_minus_one_unity_license" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
for unity_guard_consumer in \
  "$repo_root/scripts/check-one-plus-one-minus-one-unity-license.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-playmode.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-webgl.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-qa.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh" \
  "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
do
  if grep -Fq "license --json" "$unity_guard_consumer"; then
    echo "Unity license query should stay centralized in lib-one-plus-one-minus-one-unity-license.sh: $unity_guard_consumer" >&2
    exit 1
  fi
done
grep -Fq "Store-capture build is stale" "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
grep -Fq "App Store candidate screenshot is older than the store-capture build" "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
grep -Fq "Unexpected stale App Store candidate directory" "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
grep -Fq "WebGL QA build is stale" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "QA capture is older than the QA build" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "Unexpected stale QA round capture directory" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "Unexpected stale round-select capture directory" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "verify-one-plus-one-minus-one-png-visuals.mjs" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "QA key-round/page captures" "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
grep -Fq "WebGL shell metadata" "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
grep -Fq "verify-one-plus-one-minus-one-webgl-shells.sh" "$project/README.md"
grep -Fq "visual QA capture refresh completed" "$repo_root/scripts/refresh-one-plus-one-minus-one-visual-qa.sh"
grep -Fq "TextureFormat.RGB24" "$project/Assets/_Project/Editor/GenerateAppIcon.cs"
grep -Fq "small-icon visual verification" "$repo_root/scripts/verify-one-plus-one-minus-one-icon-visuals.mjs"
grep -Fq "Character policy violation" "$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
grep -Fq "ReleaseCompactMaxEquationRows" "$project/Assets/_Project/Scripts/OnePlusOneMinusOneController.cs"
grep -Fq "release-active QA/test hook" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq 'trimmed.startsWith("#elif ")' "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "branchMatched" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "iOS release build should be non-development device SDK and require production AdMob IDs" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "Android AAB release build should be an app bundle without forced test ads" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "Android production AdMob IDs should be required for non-test AAB builds" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "store metadata verification" "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "conservative submission budget" "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "require_capture_slug" "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
grep -Fq "PNG visual verification" "$repo_root/scripts/verify-one-plus-one-minus-one-png-visuals.mjs"

echo "1 = 1 static verification suite passed."
