#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
project="$repo_root/prototypes/one-plus-one-minus-one"
release_env="$project/RELEASE_ENV.example"
store_metadata="$repo_root/docs/one-equals-one-store-metadata-draft.md"
privacy_policy="$repo_root/docs/privacy-policy.md"

bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-qa.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
bash -n "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-build.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-ship-ready.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-webgl-qa-rounds.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-round-select-pages.sh"
bash -n "$repo_root/scripts/capture-one-plus-one-minus-one-app-store-candidates.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
bash -n "$repo_root/scripts/refresh-one-plus-one-minus-one-visual-qa.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-icon.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
bash -n "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
node --check "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-viewports.mjs"
node --check "$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs"
node --check "$repo_root/scripts/strip-png-alpha.mjs"
node --check "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"

"$repo_root/scripts/verify-one-plus-one-minus-one-rounds.mjs"
"$repo_root/scripts/report-one-plus-one-minus-one-round-quality.mjs" --strict
"$repo_root/scripts/verify-one-plus-one-minus-one-icon.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
"$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"
"$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-build.sh"
"$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"

grep -Fq "Bundle ID: \`com.mannlab.games.oneplusoneminusone\`" "$store_metadata"
grep -Fq "Privacy policy URL: \`https://games.mannlab.app/privacy\`" "$store_metadata"
grep -Fq "1 = 1 may use Firebase Analytics" "$privacy_policy"
grep -Fq "Strict readiness rejects" "$project/STORE_READINESS.md"
grep -Fq "NSPrivacyAccessedAPICategoryUserDefaults" "$project/Assets/_Project/Store/PrivacyInfo.xcprivacy"
grep -Fq "CA92.1" "$project/Assets/_Project/Store/PrivacyInfo.xcprivacy"
grep -Fq "AddPrivacyManifestToXcodeProject" "$project/Assets/_Project/Editor/BuildIosXcode.cs"
grep -Fq "PrivacyInfo.xcprivacy" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_IOS_APP_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_IOS_INTERSTITIAL_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_ANDROID_APP_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ADMOB_ANDROID_INTERSTITIAL_ID" "$release_env"
grep -Fq "MANNLAB_ONE_PLUS_ONE_MINUS_ONE_ANDROID_KEYSTORE_PATH" "$release_env"
grep -Fq "intentionally fail strict readiness" "$release_env"
grep -Fq "Production AdMob env uses a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-admob-crashlytics-readiness.sh"
grep -Fq "Production iOS AdMob App ID is a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-ios-readiness.sh"
grep -Fq "Production Android AdMob App ID is a placeholder" "$repo_root/scripts/verify-one-plus-one-minus-one-android-readiness.sh"
grep -Fq "Unable to open local WebGL smoke port" "$repo_root/scripts/smoke-one-plus-one-minus-one-webgl-viewports.mjs"
grep -Fq "No Unity Editor license found" "$repo_root/scripts/verify-one-plus-one-minus-one-webgl-store-capture.sh"
grep -Fq "Store-capture build is stale" "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
grep -Fq "App Store candidate screenshot is older than the store-capture build" "$repo_root/scripts/verify-one-plus-one-minus-one-app-store-candidates.sh"
grep -Fq "WebGL QA build is stale" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "QA capture is older than the QA build" "$repo_root/scripts/verify-one-plus-one-minus-one-qa-captures.sh"
grep -Fq "visual QA capture refresh completed" "$repo_root/scripts/refresh-one-plus-one-minus-one-visual-qa.sh"
grep -Fq "TextureFormat.RGB24" "$project/Assets/_Project/Editor/GenerateAppIcon.cs"
grep -Fq "Character policy violation" "$repo_root/scripts/verify-one-plus-one-minus-one-character-policy.sh"
grep -Fq "ReleaseCompactMaxEquationRows" "$project/Assets/_Project/Scripts/OnePlusOneMinusOneController.cs"
grep -Fq "release-active QA/test hook" "$repo_root/scripts/verify-one-plus-one-minus-one-release-safety.mjs"
grep -Fq "store metadata verification" "$repo_root/scripts/verify-one-plus-one-minus-one-store-metadata.sh"

if [[ "$project/Assets/_Project/Editor/GenerateAppIcon.cs" -nt "$project/Assets/_Project/Art/AppIcon-1024.png" ]]; then
  echo "Warning: AppIcon-1024.png is older than GenerateAppIcon.cs; regenerate the icon in Unity." >&2
fi

echo "1 = 1 static verification suite passed."
